In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.6'

#getting data, already done in practice.ipynb

In [3]:
#Q1
data=pd.read_csv("car_fuel_efficiency.csv")

In [4]:
#Q2
data.shape

(9704, 11)

In [5]:
data.value_counts("fuel_type")
data["fuel_type"].unique()
#both work

<StringArray>
['Gasoline', 'Diesel']
Length: 2, dtype: str

In [6]:
data.isna().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [7]:
d1=data[(data["origin"]=="Asia")]
d1

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
20,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083
21,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730
...,...,...,...,...,...,...,...,...,...,...,...
9688,260,4.0,NaN,3948.404625,15.5,2018,Asia,Diesel,All-wheel drive,-1.0,11.054830
9692,180,3.0,188.0,3680.341381,18.0,2016,Asia,Gasoline,Front-wheel drive,1.0,11.711653
9693,280,2.0,148.0,2545.070139,15.6,2012,Asia,Diesel,All-wheel drive,0.0,17.202782
9698,180,1.0,131.0,3107.427820,13.2,2005,Asia,Gasoline,Front-wheel drive,-2.0,13.933716
9703,270,3.0,140.0,2908.043477,14.7,2005,Asia,Diesel,All-wheel drive,-1.0,14.884467

In [8]:
maxi=d1["fuel_efficiency_mpg"].max()

In [9]:
print(maxi)

23.759122836520497

In [10]:
#Q6.1
horse=data["horsepower"].median()
print(horse)
#

149.0

In [11]:
#Q6.2   
print(data.value_counts("horsepower").idxmax())

152.0

In [12]:
#Q6.3   
fill=data.value_counts("horsepower").idxmax()
hp_filled=data["horsepower"].fillna(fill)

In [13]:
hp_filled.isnull().sum()

np.int64(0)

In [14]:
median_after=hp_filled.median()

In [15]:
print(horse,median_after)

149.0 152.0

Q7

In [16]:
data=pd.read_csv("car_fuel_efficiency.csv")
data.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [17]:
data_asia=data[data["origin"]=="Asia"]

In [18]:
data_asia.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
12,320,5.0,145.0,2783.868974,15.1,2010,Asia,Diesel,All-wheel drive,1.0,16.175820
14,200,6.0,160.0,3582.687368,14.9,2007,Asia,Diesel,All-wheel drive,0.0,11.871091
20,150,3.0,197.0,2231.808142,18.7,2011,Asia,Gasoline,Front-wheel drive,1.0,18.889083
21,160,4.0,133.0,2659.431451,NaN,2016,Asia,Gasoline,Front-wheel drive,-1.0,16.077730

In [23]:
data_filtered=data_asia[["vehicle_weight","model_year"]].head(7)

In [24]:
data_filtered

    vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [ ]:

X=data_filtered[["vehicle_weight","model_year"]].values
print(X)

[[2714.21930965 2016.        ]
 [2783.86897424 2010.        ]
 [3582.68736772 2007.        ]
 [2231.8081416  2011.        ]
 [2659.43145076 2016.        ]
 [2844.22753389 2014.        ]
 [3761.99403819 2019.        ]]

In [39]:
XTX=(X.T@X)
#2,7 * 7,2

In [40]:
invXTX=np.linalg.inv(XTX)

In [41]:
y=[1100, 1300, 800, 900, 1000, 1100, 1200]

In [42]:
print(y)

[1100, 1300, 800, 900, 1000, 1100, 1200]

In [43]:
print(XTX)

[[62248334.33150762 41431216.5073268 ]
 [41431216.5073268  28373339.        ]]

In [49]:
w=invXTX@X.T@y

In [50]:
print(w)

[0.01386421 0.5049067 ]

In [52]:
print (sum(w))

0.5187709081074016